### ISSUE TITLE
Add laravel example

### ISSUE THREAD

**Issue by abcdmitry** [TetraWeb/docker#35]

**Comment by mariomka** [comment]
Here my .gitlab-ci.yml for a laravel 5.2 project with postgre:

``` yml
# Before script
before_script:
  - docker-php-ext-enable mbstring
  - docker-php-ext-enable zip
  - docker-php-ext-enable pdo_pgsql
  - composer self-update
  - composer install --prefer-dist --no-ansi --no-interaction
  - cp .env.ci .env
  - php artisan key:generate
  - php artisan migrate:refresh --seed

# Variables
variables:
  POSTGRES_DB: gitlabci
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: secret
  COMPOSER_GITHUB: <YOUR GITHUB TOKEN>

# PHP
php:
  image: tetraweb/php:7.0
  services:
    - postgres:latest
  script:
    - php vendor/bin/phpunit --debug
```

And a ci.env example file

``` ini
APP_ENV=local
APP_DEBUG=true
APP_KEY=SomeRandomString
APP_URL=http://localhost

DB_CONNECTION=pgsql
DB_HOST=postgres
DB_DATABASE=gitlabci
DB_USERNAME=runner
DB_PASSWORD=secret

CACHE_DRIVER=file
SESSION_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
```
